[WIP] [GOLD] Adapting scripts for new TBB
oneapi-src/oneDAL pull request #1116
Opened 2020-10-16 21:25 UTC by homksei

2020-10-28 08:55 UTC, napetrov commented
/intelci: run

2020-10-28 08:57 UTC, averbukh requested changes

2020-10-28 08:57 UTC, averbukh commented on makefile
> +TBBDIR.2 := $(if $(TBBDIR.2),$(TBBDIR.2),$(error Can`t find TBB neither in $(DIR)/__deps/tbb not in $$TBBROOT))
Before your changes it was correct: "neither... nor..."

2020-10-28 13:03 UTC, averbukh approved these changes

2020-10-29 14:33 UTC, homksei commented
/intelci: run
set infra_branch=dev/alekseik/GOLD/Tools_update

2020-10-29 18:11 UTC, merged

2020-10-31 07:27 UTC, napetrov commented
@Mergifyio backport master