fix conformance for PCA, KMeans and KMeans init constructors
oneapi-src/oneDAL pull request #1222
Opened 2020-10-28 16:57 UTC by mchernov-intel

2020-10-28 17:01 UTC, rlnx reviewed
I think examples should remain unchanged

2020-10-29 18:13 UTC, KulikovNikita requested changes

2020-10-29 18:13 UTC, KulikovNikita commented on cpp/oneapi/dal/algo/pca/common.hpp
> +    }
Is it correct? At least it's useless to run PCA with zero components

2020-10-29 18:13 UTC, KulikovNikita commented on examples/oneapi/cpp/source/kmeans/kmeans_lloyd_dense_batch.cpp
> +        const auto kmeans333_desc = dal::kmeans::descriptor<>();
Please check indent

2020-10-29 18:13 UTC, KulikovNikita commented on examples/oneapi/cpp/source/pca/pca_dense_batch.cpp
> +    const auto pca_desc = dal::pca::descriptor<float, Method>(5)
```suggestion
    const auto pca_desc = dal::pca::descriptor<float, Method>(/*component_count = */5)
```
I see lack of explicitness here. Maybe proposed code is better

2020-10-30 05:29 UTC, mchernov-intel commented
/intelci: run

2020-10-30 18:57 UTC, rlnx approved these changes

2020-10-31 14:42 UTC, KulikovNikita approved these changes

2020-10-31 18:18 UTC, merged