SSSP unit tests
oneapi-src/oneDAL pull request #1729
Opened 2021-06-17 10:25 UTC by YakhtinLeonid

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/badargs.cpp
> +
Is this empty blank required by the general testing design? If no, remove.

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/badargs.cpp
> +        auto result_type = nothing_to_calculate
to compute

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/badargs.cpp
> +                alloc);
Why do we need this?  std alloc is the default type and default constructor as a default value.

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +class d_thread_buckets_type : public graph_base_data {
d_thread... is not a clear naming

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +                                     std::numeric_limits<float>::infinity(),
create an alias or constexpr var with clear short name.

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +                                     std::numeric_limits<float>::infinity(),
Why std vector? Can we use an array?

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +                                     static_cast<float>(std::numeric_limits<int32_t>::max()),
Why cast?

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +                                     static_cast<float>(std::numeric_limits<int32_t>::max()),
Why distances are float type?

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +    bool operator!=(const LimitedAllocator<U>&) const noexcept {
Why do you need == and !=

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +    typedef T* pointer;
unused?

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +    typedef T* pointer;
Check std allocator traits requirements for the allocator and cover the only required things

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +    size_t max_allocation_size;
Initial value?

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +float get_inf_value() {
constexpr

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +    const float kEps = 5e-5;
Why do we use this value?

2021-06-17 10:52 UTC, orrrrtem commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +        auto arr = oneapi::dal::row_accessor<const float>(table).pull();
Why always float?

2021-06-21 22:23 UTC, YakhtinLeonid commented
/intelci: run

2021-06-22 12:17 UTC, YakhtinLeonid commented
/intelci: run

2021-06-23 09:34 UTC, YakhtinLeonid commented
/intelci: restart

2021-06-30 13:33 UTC, YakhtinLeonid commented
/intelci: restart

2021-07-02 08:24 UTC, bysheva requested changes

2021-07-02 08:24 UTC, bysheva commented on cpp/oneapi/dal/algo/shortest_paths/test/badargs.cpp
> +    int source;
Probably source should be int64 as defined in algorithm

2021-07-02 08:24 UTC, bysheva commented on cpp/oneapi/dal/algo/shortest_paths/test/badargs.cpp
> +    // REQUIRE_THROWS_AS((this->check_shortest_paths<example_graph_type>(0, 0)), invalid_argument);
Is it obsolete comment? should we remove it?

2021-07-02 08:24 UTC, bysheva commented on cpp/oneapi/dal/algo/shortest_paths/test/badargs.cpp
> +// SHORTEST_PATHS_BADARG_TEST("Check edges are non-negative") {
Is it obsolete comment? should we remove it?

2021-07-02 08:24 UTC, bysheva commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_graphs.hpp
> +    int source;
The same, source is int64

2021-07-02 08:24 UTC, bysheva commented on cpp/oneapi/dal/algo/shortest_paths/test/shortest_paths_test.cpp
> +// SHORTEST_PATHS_TEST("Custom allocator with limited allocations (cannot allocate enough memory)"){
Obsolete comment?

2021-07-02 09:42 UTC, YakhtinLeonid commented
/intelci: run

2021-07-02 10:02 UTC, bysheva approved these changes

2021-07-04 18:00 UTC, merged