Add graph service functions tests
oneapi-src/oneDAL pull request #1775
Opened 2021-07-12 21:55 UTC by Plastova

2021-07-12 21:57 UTC, Plastova commented
/intelci: run

2021-07-13 06:13 UTC, Plastova commented
/intelci: run

2021-07-20 14:02 UTC, orrrrtem submitted a review, later dismissed
static asserts related comments need to be removed.
Incorrect results to be reported at least in the backlog.

2021-07-22 07:57 UTC, bysheva requested changes

2021-07-22 07:57 UTC, bysheva commented on cpp/oneapi/dal/graph/test/badarg.cpp
> +//incorrect result
Probably need to remove these comments

2021-07-22 07:57 UTC, bysheva commented on cpp/oneapi/dal/graph/test/badarg.cpp
> +// SERVICE_FUNCTIONS_BADARG_TEST("Directed graph for get_vertex_degree") {
Also to remove unnecessary comments

2021-07-30 07:57 UTC, Plastova commented
/intelci: run

2021-08-02 08:04 UTC, bysheva approved these changes

2021-08-03 08:50 UTC, merged