SPMD communicator allgatherv method to support arbitrary displacements
oneapi-src/oneDAL pull request #2068
Opened 2022-02-04 07:46 UTC by VadimVoevodkin

2022-02-04 07:46 UTC, VadimVoevodkin commented
intelci: run

2022-02-04 08:11 UTC, VadimVoevodkin commented
intelci: run

2022-02-07 13:39 UTC, amgrigoriev commented on cpp/oneapi/dal/detail/ccl/communicator.hpp
> +        std::int64_t data_type_size = get_data_type_size(dtype);
```suggestion
        const std::int64_t data_type_size = get_data_type_size(dtype);
```

2022-02-09 09:18 UTC, amgrigoriev commented
/intelci: run

2022-02-09 11:53 UTC, amgrigoriev requested changes
Please add mpi/ccl tests for arbitrary displacements

2022-02-11 12:28 UTC, amgrigoriev commented on cpp/oneapi/dal/test/ccl_communicator.cpp
> +        recv_counts[i] = (i + 2) * granularity;
The idea is not to increase receive count for every rank but to add a gap between results obtained from different ranks, Please also add a constant for gap width. Initial array should be filled by -1 (or any other values that are different against collected values) and values inside gaps should remain unchanged after allgatherv call.

2022-02-14 14:50 UTC, VadimVoevodkin commented
/intelci: run

2022-02-14 16:25 UTC, amgrigoriev commented on cpp/oneapi/dal/test/ccl_communicator.cpp
> +    std::vector<std::int64_t> recv_counts_final_buf(rank_count);
Please use shorter name: recv_counts, for instance.

2022-03-11 09:10 UTC, VadimVoevodkin commented
/intelci: run

2024-03-07 10:58 UTC, closed without merging