FIX: kmeans bad alloc issue
oneapi-src/oneDAL pull request #2134
Opened 2022-10-14 21:51 UTC by samir-nasibli

# Description
The issue is under investigation.
Note: please do not merge.
TBD

2022-10-26 18:34 UTC, Alexandr-Solovev approved these changes

2022-10-26 18:36 UTC, Alexandr-Solovev requested changes
Use clang format to fix ci error

2022-10-27 13:20 UTC, Alexsandruss approved these changes

2022-10-27 18:25 UTC, Alexandr-Solovev approved these changes

2022-10-27 20:52 UTC, merged