Dev/logloss
oneapi-src/oneDAL pull request #2242
Opened 2023-01-16 11:21 UTC by avolkov-intel

Add logloss primitive which also can compute hessian and derivative

2023-01-16 11:42 UTC, samir-nasibli commented
I see some conflicts. Please, rebase your branch.

2023-01-16 11:42 UTC, samir-nasibli commented on cpp/oneapi/dal/backend/primitives/blas/gemv.hpp
> +* Copyright 2022 Intel Corporation
2023

2023-01-16 11:44 UTC, KulikovNikita requested changes

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/blas/gemv.hpp
> +* Copyright 2022 Intel Corporation
Please fix year

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/blas/gemv_dpc.cpp
> +* Copyright 2022 Intel Corporation
Year

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +    auto fill_event = fill<Float>(q, probabilities, Float(1), {});
Check that shapes of ndviews are correct and that they have data.

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +    event_vector vector_out_reg = { out_reg_e };
What is the purpose to store it as a vector? I see no place where this vector is modified

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +    auto param_ptr = parameters.get_data();
Please use `const auto* const` for pointers to constant data and `auto* const` for pointers to modifiable data

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +    const std::int64_t block_size = 32;
```suggestion
    constexpr std::int64_t block_size = 32;
```

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +                for (auto i = obj_ind * block_size; i < std::min((obj_ind + 1) * block_size, n);
```suggestion
                const auto last_ind = std::min((obj_ind + 1) * block_size, n);
                for (auto i = obj_ind * block_size; i < last_ind;
```

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        //const auto parameters = GENERATE_DATAFRAME(te::dataframe_builder{ 1, p_ + 1}.fill_uniform(-2, 2));
Please delete all commented lines

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +                  << "ms" << std::endl;
Please delete "benchmrking" and output

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +                  << "ms" << std::endl;
The same

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_perf_dpc.cpp
> +        std::cout << "Size: " << n_ << " " << p_ << std::endl;
output

2023-01-16 11:44 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_perf_dpc.cpp
> +} // namespace oneapi::dal::backend::primitives::test
Please fix EOF

2023-01-17 11:15 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_perf_dpc.cpp
> +* Copyright 2022 Intel Corporation
Year

2023-01-17 11:15 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/reduction/reduction_1d.hpp
> +* Copyright 2022 Intel Corporation
Year

2023-01-17 11:15 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/reduction/reduction_1d_dpc.cpp
> +* Copyright 2022 Intel Corporation
Year

2023-01-17 11:15 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/reduction/test/reduction_1d_dpc.cpp
> +* Copyright 2022 Intel Corporation
Year

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +    event_vector vector_out_reg = { out_reg_e };
```suggestion
    const event_vector vector_out_reg = { out_reg_e };
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +
empty line

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        float_t L2 = 0.7;
```suggestion
        constexpr float_t L1 = 1.2;
        constexpr float_t L2 = 0.7;
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        const float_t cur_param[p + 1] = { -0.2, 0.1, -1, 0.4 };
```suggestion
        constexpr float_t data[n * p] = {
            0.83731708, -0.70899924, -1.23362082, 0.23468538, -0.10549413,
            1.12902673, -0.61035703, -1.55617932, 0.60419908, 0.30589827,
            0.63919892, -0.23380754, 2.38196927,  1.64158111, 0.13677077
        };
        constexpr std::int32_t labels[n] = { 0, 1, 1, 0, 1 };
        constexpr float_t L1 = 2.3456;
        constexpr float_t L2 = 3.123;
        constexpr float_t cur_param[p + 1] = { -0.2, 0.1, -1, 0.4 };
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        std::int64_t p = data_host.get_dimension(1);
```suggestion
        const std::int64_t n = data_host.get_dimension(0);
        const std::int64_t p = data_host.get_dimension(1);
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        constexpr float_t eps = sizeof(float_t) >= 8 ? 1e-6 : 1e-4; //1e-4;
```suggestion
        constexpr float_t rtol = sizeof(float_t) > 4 ? 1e-6 : 1e-4;
        constexpr float_t atol = sizeof(float_t) > 4 ? 1e-6 : 1e-4;
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        check_val(val_logloss, logloss, eps);
```suggestion
        check_val(val_logloss, logloss, rtol, atol);
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        float_t val_logloss = out_logloss.to_host(this->get_queue(), {}).at(0);
```suggestion
        const float_t val_logloss1 = out_logloss.to_host(this->get_queue(), {}).at(0);
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        val_logloss = out_logloss.to_host(this->get_queue(), {}).at(0);
```suggestion
        const auto val_logloss2 = out_logloss.to_host(this->get_queue(), {}).at(0);
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +    void test_input(const ndarray<float_t, 2>& data_host,
Try to split into the smaller functions

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        float_t logloss = test_predictions_and_logloss(data_host,
```suggestion
        const float_t logloss = test_predictions_and_logloss(data_host,
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        }
Please check

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_perf_dpc.cpp
> +        float_t L2 = 0.7;
```suggestion
        constexpr float_t L1 = 1.2;
        constexpr float_t L2 = 0.7;
```

2023-01-17 15:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_perf_dpc.cpp
> +                                                              { fill_event, out_der_e });
You need to measure perf only for this section

2023-01-20 10:58 UTC, KulikovNikita approved these changes
Minor fixes required. Please take and fix

2023-01-20 10:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +    event_vector vector_out_reg = { out_reg_e };
Still valid

2023-01-20 10:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +
Still valid

2023-01-20 10:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +                long double prob = probabilities.at(i);
As far as I know `long double` == `double` for the absolute majority of systems

2023-01-20 10:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        float_t cur_param[MAXN];
Please use safer alternative:

```suggestion
        std::array<float_t, max_n> cur_param;
```

2023-01-20 10:58 UTC, KulikovNikita commented on cpp/oneapi/dal/backend/primitives/objective_function/test/logloss_dpc.cpp
> +        constexpr std::int64_t MAXN = 2000;
```suggestion
        constexpr std::int64_t max_n = 2000;
```

2023-01-20 11:39 UTC, KulikovNikita commented
I believe you can merge it after passing CI

2023-01-20 11:39 UTC, KulikovNikita commented
/intelci: run

2023-01-23 12:12 UTC, avolkov-intel commented
/intelci: run

2023-01-24 10:41 UTC, avolkov-intel commented
/intelci: run

2023-01-24 11:18 UTC, avolkov-intel commented
/intelci: rerun

2023-01-27 10:12 UTC, avolkov-intel commented
/intelci: run

2023-01-30 09:45 UTC, avolkov-intel commented
/intelci: rerun

2023-01-31 09:33 UTC, avolkov-intel commented
/intelci: run

2023-01-31 15:17 UTC, merged