Coverity hits fixes
oneapi-src/oneDAL pull request #2475
Opened 2023-08-25 13:07 UTC by inteldimitrius

# Description
Fixes coverity hits.

2023-08-25 13:11 UTC, ethanglaser commented
/intelci: run

2023-08-25 13:11 UTC, Alexandr-Solovev approved these changes
LGTM

2023-08-25 13:51 UTC, avolkov-intel requested changes

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/include/services/collection.h
I see that after that code there is another cycle that goes over _array https://github.com/oneapi-src/oneDAL/blob/38ecb335aa5f72297abfba7920a809788d33add7/cpp/daal/include/services/collection.h#L245
I think it should also be moved inside if-statement

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/dbscan/dbscan_result_types.cpp
I suggest to create new status ErrorIncorrectInput (or ErrorDynamicCastFailed) because status ErrorIncorrectParameter is misleading.

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/distributions/uniform/uniform_impl.i
Maybe we should also change the name of status here

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_container.h
DAAL_ASSERT seems redundant

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_train_dense_default_impl.i
I think we should throw exception if condition is not satisfied

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/dtrees/forest/classification/df_classification_training_types.cpp
Add throw exception if algParameter3 is NULL. Moreover, this check should be right after the dynamic cast (above line 112)

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
Return error status if condition is not satisfied

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/daal/src/algorithms/pca/pca_result.cpp
throw exception or return error status if it  is not NULL

2023-08-25 13:51 UTC, avolkov-intel commented on cpp/oneapi/dal/detail/common.hpp
I think the original code was correct, and the change will break it

2023-08-25 13:55 UTC, inteldimitrius commented on cpp/daal/include/services/collection.h
It is okay, becuase down in the _array is reassigned. 
In fact it is resize() method for collection. So it creates new array and tries to copy (previously unsafe) existing array.

2023-08-25 14:27 UTC, inteldimitrius commented on cpp/daal/src/algorithms/dtrees/forest/regression/df_regression_train_dense_default_impl.i
It is okay for splitter not to have best split. It is normal scenario when node will just remain a leaf.

2023-08-25 14:32 UTC, inteldimitrius commented on cpp/daal/src/algorithms/pca/pca_result.cpp
I added else case with empty constructor in case if previous result is not available.

2023-08-25 15:41 UTC, ethanglaser commented
/intelci: run

2023-08-25 17:01 UTC, ethanglaser commented
Looks like one test failure - //cpp/oneapi/dal/algo/decision_forest:test_spmd_dpc - is it reproducible locally? I think its a new failure.

2023-08-25 20:59 UTC, ethanglaser commented
> 

Never mind, its from master

2023-08-25 21:00 UTC, ethanglaser commented
> Looks like one test failure - //cpp/oneapi/dal/algo/decision_forest:test_spmd_dpc - is it reproducible locally? I think its a new failure.

Never mind, seems its from master

2023-08-28 08:17 UTC, avolkov-intel approved these changes

2023-08-28 12:05 UTC, ethanglaser commented
/intelci: run

2023-08-28 17:27 UTC, merged