coverity fixes 2024.0.1
oneapi-src/oneDAL pull request #2575
Opened 2023-11-13 12:12 UTC by icfaust

# Description
Fixing a default value hit for gbt classification

Changes proposed in this pull request:
- add default value to gbt classification ModelImpl

2023-11-13 12:32 UTC, icfaust commented
/intelci: run

2023-11-14 08:26 UTC, ahuber21 requested changes

2023-11-14 08:26 UTC, ahuber21 commented on cpp/daal/src/algorithms/dtrees/gbt/classification/gbt_classification_model_impl.h
> +    ModelImpl(size_t nFeatures = 0) : ClassificationImplType(nFeatures), _predictionBias(0.) {}
```suggestion
    ModelImpl(size_t nFeatures = 0) : ClassificationImplType(nFeatures), _predictionBias(0.0f) {}
```

2023-11-14 08:26 UTC, ahuber21 commented on cpp/daal/src/algorithms/dtrees/gbt/regression/gbt_regression_model_impl.h
> +    ModelImpl(size_t nFeatures = 0) : RegressionImplType(nFeatures), _predictionBias(0.) {}
```suggestion
    ModelImpl(size_t nFeatures = 0) : RegressionImplType(nFeatures), _predictionBias(0.0f) {}
```

2023-11-14 08:28 UTC, icfaust commented
/intelci: run

2023-11-14 08:32 UTC, ahuber21 approved these changes
Approved, assuming green CI

2023-11-14 11:51 UTC, Vika-F approved these changes
LGTM

2023-11-14 12:21 UTC, merged