fix: forest coverity issues
oneapi-src/oneDAL pull request #2657
Opened 2024-02-06 14:07 UTC by Alexandr-Solovev

# Description
Please include a summary of the change. For large or complex changes please include enough information to introduce your change and explain motivation for it.

Changes proposed in this pull request:
-
-
-

2024-02-12 16:05 UTC, ahuber21 commented on cpp/daal/src/algorithms/dtrees/dtrees_train_data_helper.i
> +          left {}
Isn't it best practice to instantiate in the same order we declare in the class?

2024-02-12 16:52 UTC, Alexsandruss commented
@mergifyio rebase

2024-02-12 16:54 UTC, Alexsandruss requested changes
Correct args order for SplitData

2024-02-12 18:33 UTC, icfaust commented
/intelci: run

2024-02-13 14:38 UTC, icfaust commented
/intelci: run

2024-02-15 14:11 UTC, Alexandr-Solovev commented
/intelci: run

2024-02-15 20:26 UTC, Alexsandruss approved these changes

2024-02-15 20:26 UTC, merged