qemu version change
oneapi-src/oneDAL pull request #2862
Opened 2024-07-30 17:07 UTC by md-shafiul-alam

# Description
version 9.0.1 was removed, using a slightly older version to avoid frequent update.

Changes proposed in this pull request:
-
-
-

2024-07-30 18:14 UTC, napetrov commented
@keeranroth  @rakshithgb-fujitsu  - please review/comment

2024-07-31 06:02 UTC, rakshithgb-fujitsu commented
Looks fine to me. Some CI cases are failing though.

2024-07-31 07:12 UTC, keeranroth requested changes
Maybe try adding a list of packages, so that if one goes away for a few days, we have a backup

2024-07-31 07:12 UTC, keeranroth commented on .ci/env/apt.sh
> +    qemu_deb=qemu-user-static_8.2.4+ds-1_amd64.deb
This has been flaky in the past as well. Let's pass a few version numbers through, and get the first one that exists. Something like the following seems to work (feel free to tidy up / change as necessary

```
set +e

versions=(9.0.2 9.0.1 8.2.4)
found_version=""
for version in ${versions[@]}; do
    qemu_deb="qemu-user-static_${version}+ds-1_amd64.deb"
    echo "Checking for http://ftp.debian.org/debian/pool/main/q/qemu/${qemu_deb}"
    if wget -q --method=HEAD http://ftp.debian.org/debian/pool/main/q/qemu/${qemu_deb} &> /dev/null;
    then
        echo "Found qemu version ${version}"
        found_version=${qemu_deb}
        break
    fi
done

set -eo pipefail
if [[ -z "${found_version}" ]] ; then
    # If nothing is found, error out and fail
    echo "No qemu found with version numbers ${versions[@]}"
    false
fi

wget http://ftp.debian.org/debian/pool/main/q/qemu/${found_version}
sudo dpkg -i ${found_version}
```

2024-07-31 19:45 UTC, keeranroth approved these changes
Looks good to me. I don't think that the failures in the other pipelines are related, from a quick look

2024-07-31 19:56 UTC, md-shafiul-alam commented
> Looks good to me. I don't think that the failures in the other pipelines are related, from a quick look

agree, thanks for the great suggestion

2024-07-31 20:24 UTC, ethanglaser approved these changes

2024-07-31 20:25 UTC, ethanglaser commented
LinuxSklearnex fail will be addressed by https://github.com/intel/scikit-learn-intelex/pull/1982

2024-07-31 20:27 UTC, merged