Add missing dependencies to compute probabilities function
oneapi-src/oneDAL pull request #2904
Opened 2024-09-18 17:58 UTC by avolkov-intel

# Description
Add missing dependency for at_device function and resolve logreg test failures

2024-09-19 11:06 UTC, samir-nasibli commented
Please share stable jobs for this fixes with sklearnex tests deselected

2024-09-19 12:00 UTC, avolkov-intel commented
CI: http://intel-ci.intel.com/ef767e7e-f951-f12d-8dba-a4bf010d0e2e

2024-09-19 12:37 UTC, samir-nasibli commented
> CI: http://intel-ci.intel.com/ef767e7e-f951-f12d-8dba-a4bf010d0e2e

Here sklearnex branch main branch, where this test is deselected. Please update and share the run with the scikit-learn-intelex spmd logreg test deselected

2024-09-19 14:19 UTC, avolkov-intel commented
rerun on rebased branch: http://intel-ci.intel.com/ef7691b7-b396-f153-808d-a4bf010d0e2e

2024-09-19 14:21 UTC, avolkov-intel commented
CI with enabled test: http://intel-ci.intel.com/ef769255-f5cf-f10a-99ec-a4bf010d0e2e

2024-09-23 07:40 UTC, Alexandr-Solovev commented on cpp/oneapi/dal/backend/primitives/objective_function/logloss_dpc.cpp
> +        fit_intercept ? parameters.get_slice(0, 1).at_device(q, 0l, deps) : 0; // Poor perfomance
if the fill event has no deps with w0 computation looks good

2024-09-23 07:40 UTC, Alexandr-Solovev approved these changes

2024-09-23 09:40 UTC, samir-nasibli reviewed
Please rebase and re-run CI checks

2024-09-23 09:45 UTC, samir-nasibli requested changes
@avolkov-intel I don't see that sklearnex branch has changes for deselecting required spmd tests for logreg. Please address comments and rebase your branches for the check

2024-09-23 11:58 UTC, avolkov-intel commented
/intelci: run

2024-09-23 18:52 UTC, avolkov-intel commented
CI with enabled test: http://intel-ci.intel.com/ef79c8a7-7928-f1dd-a4c8-a4bf010d0e2d

2024-09-24 09:21 UTC, samir-nasibli commented
@avolkov-intel please provide the job with the rebased sklearnex main branch with spmd logreg test deselection + current branch

2024-09-24 12:47 UTC, avolkov-intel commented
http://intel-ci.intel.com/ef7a5922-4eeb-f191-958d-a4bf010d0e2d

2024-09-24 12:52 UTC, samir-nasibli commented
> http://intel-ci.intel.com/ef7a5922-4eeb-f191-958d-a4bf010d0e2d

@avolkov-intel all spmd sklearnex tests are skipped. Could you please check what it the issue?
```bash
spmd/linear_model/tests/test_logistic_regression_spmd.py sssssssssssssss [ 51%]
ssssssssssssssssssssssssssssssssss    
```

2024-09-24 13:13 UTC, samir-nasibli commented
> > http://intel-ci.intel.com/ef7a5922-4eeb-f191-958d-a4bf010d0e2d
> 
> @avolkov-intel all spmd sklearnex tests are skipped. Could you please check what it the issue?
> 
> ```shell
> spmd/linear_model/tests/test_logistic_regression_spmd.py sssssssssssssss [ 51%]
> ssssssssssssssssssssssssssssssssss    
> ```

Wrong place was looking. Looks good now.
Please rebase your branch and merge

2024-09-24 13:15 UTC, merged